# Generated by Django 4.1.4 on 2023-03-05 21:44

from django.db import migrations, models
import django.template.defaulttags


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=130, unique=True)),
                ('Cantidad', models.IntegerField(default='')),
                ('Mantenimiento', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('precio_maquinaria', models.IntegerField(default=0)),
                ('fecha_compra_maquinaria', models.DateField(default=django.template.defaulttags.now)),
            ],
            options={
                'ordering': ('Descripcion',),
            },
        ),
    ]
