# Generated by Django 4.1.4 on 2023-03-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0002_alter_maquinaria_fecha_compra_maquinaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinaria',
            name='Mantenimiento',
            field=models.CharField(default=None, max_length=5),
        ),
    ]
