# Generated by Django 4.1.4 on 2023-03-05 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finanzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.DateField(default=django.utils.timezone.now)),
                ('mes', models.DateField(default=django.utils.timezone.now)),
                ('mensualidades', models.IntegerField(default=None)),
                ('ingresos', models.IntegerField(default=None)),
                ('gastos', models.IntegerField(default=None)),
                ('ganancias', models.IntegerField(default=None)),
            ],
        ),
    ]
