# Generated by Django 4.1.5 on 2023-03-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_alter_finanzas_anio_alter_finanzas_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='finanzas',
            name='perdidas',
            field=models.IntegerField(default=None),
        ),
    ]
