# Generated by Django 4.1.5 on 2023-03-14 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_finanzas_perdidas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finanzas',
            name='perdidas',
        ),
    ]
