# Generated by Django 4.1.4 on 2023-01-25 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del cliente', max_length=100)),
                ('apellido', models.CharField(help_text='Ingrese el apellido del cliente', max_length=100)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, null=True)),
                ('cedula', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('edad', models.IntegerField(default=0, help_text='Ingrese la edad del cliente')),
                ('fecha_de_ingreso', models.DateField(default=django.utils.timezone.now, help_text='Seleccione la fecha de ingreso')),
            ],
        ),
    ]
