# Generated by Django 4.1.4 on 2023-02-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
